/*
 * Copyright (C) 2016 Lucien XU <sfietkonstantin@free.fr>
 *
 * You may use this file under the terms of the BSD license as follows:
 *
 * "Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are
 * met:
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above copyright
 *     notice, this list of conditions and the following disclaimer in
 *     the documentation and/or other materials provided with the
 *     distribution.
 *   * The names of its contributors may not be used to endorse or promote
 *     products derived from this software without specific prior written
 *     permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
 * A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
 * OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
 * SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
 * LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
 * DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
 * THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
 * (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE."
 */

// This file is autogenerated by microgen.py

#ifndef MICROCORE_${module.upper()}_QT_${name.upper()}OBJECT_H
#define MICROCORE_${module.upper()}_QT_${name.upper()}OBJECT_H

#include <QObject>
% if has_list:
#include <QList>
% endif
#include "${parent_outfile}.h"

namespace microcore { namespace ${module} { namespace qt {

% for nested_class in classes:
${nested_class["h_nested"]}
% endfor
class ${name}Object : public QObject
{
    Q_OBJECT
    % for property in properties:
    % if property["access"] == "c":
    % if property["type_type"] == "list":
    Q_PROPERTY(QList<${property["qt_type"]}> ${property["name"]} READ ${property["getter"]} CONSTANT)
    % else:
    Q_PROPERTY(${property["qt_type"]} ${property["name"]} READ ${property["getter"]} CONSTANT)
    % endif
    % elif property["access"] == "r" or property["access"] == "rw":
    % if property["type_type"] == "list":
    Q_PROPERTY(QList<${property["qt_type"]}> ${property["name"]} READ ${property["getter"]} NOTIFY ${property["name"]}Changed)
    % elif property["is_qt_object"]:
    Q_PROPERTY(${property["qt_type"]} ${property["name"]} READ ${property["getter"]} CONSTANT)
    % else:
    Q_PROPERTY(${property["qt_type"]} ${property["name"]} READ ${property["getter"]} NOTIFY ${property["name"]}Changed)
    % endif
    % endif
    % endfor
public:
    explicit ${name}Object(QObject *parent = nullptr);
    explicit ${name}Object(::microcore::${module}::${name} &&data, QObject *parent = nullptr);
    DISABLE_COPY_DISABLE_MOVE(${name}Object);
    % for property in properties:
    % if property["type_type"] == "list":
    QList<${property["qt_type"]}> ${property["getter"]}() const;
    % else:
    ${property["qt_type"]} ${property["getter"]}() const;
    % endif
    % endfor
    const ::microcore::${module}::${name} & data() const;
    void update(::microcore::${module}::${name} &&data);
% if not const:
Q_SIGNALS:
    % for property in properties:
    % if property["access"] != "c":
    % if not property["is_qt_object"] or property["type_type"] == "list":
    void ${property["name"]}Changed();
    % endif
    % endif
    % endfor
% endif
private:
    ::microcore::${module}::${name} m_data {};
    % for property in properties:
    % if property["is_qt_object"]:
    % if property["type_type"] == "list":
    QList<${property["qt_class"]} *> m_${property["name"]} {};
    % else:
    ${property["qt_class"]} *m_${property["name"]} {nullptr};
    % endif
    % endif
    % endfor
};

}}}

#endif // MICROCORE_${module.upper()}_QT_${name.upper()}OBJECT_H
